dist: trusty
language: java
jdk:
- oraclejdk8
install:
- mvn -N io.takari:maven:wrapper -Dmaven=3.5.0
- java -version && javac -version && ./mvnw -version -B
before_script:
- ./mvnw de.qaware.maven:go-offline-maven-plugin:resolve-dependencies -DdownloadSources -DdownloadJavadoc -B -Prelease-ossrh
script:
- ./mvnw clean install -B -Dgpg.skip=true
cache:
  directories:
  - $HOME/.m2